name: "OSSF Scorecard SARIF"
description: "Runs Scorecard and outputs SARIF results."
inputs:
  enabled_checks:
    description: "Comma-separated list of enabled Scorecard checks"
    required: false
    default: ""
  results_file:
    description: "Path to the SARIF results file"
    required: true
    default: results.sarif

runs:
  using: "composite"
  steps:
    - name: "Run OSSF Scorecard analysis"
      uses: ossf/scorecard-action@v2.3.0
      with:
        results_file: ${{ inputs.results_file }}
        results_format: sarif
        publish_results: false
        # Only include enabled_checks if provided; removing it uses the defaults (all checks)
        enabled_checks: ${{ inputs.enabled_checks }}
