name: "OSSF Scorecard SARIF"
description: "Runs Scorecard and outputs SARIF results."
inputs:
  checks:
    description: "Comma-separated list of Scorecard checks to enable"
    required: false
    default: ""
  results_file:
    description: "Path to the SARIF results file"
    required: true
    default: results.sarif

runs:
  using: "composite"
  steps:
    - name: "Run OSSF Scorecard analysis"
      uses: ossf/scorecard-action@v2.3.0
      with:
        results_file: ${{ inputs.results_file }}
        results_format: sarif
        publish_results: false
        checks: ${{ inputs.checks }}
