name: Build docker image with sources
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of ompzowe/app-server to use in build'
        required: true
  pull_request:
    branches: [staging]

env:
  ZOWE_DOCKER_REGISTRY: zowe-docker-snapshot.jfrog.io

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

#      - uses: zowe-actions/shared-actions/envvars-global@main
        
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - uses: zowe-actions/shared-actions/docker-sources-local@feature/get-docker-sources
        with:
          image-name: zowe-docker-snapshot.jfrog.io/ompzowe/app-server:1.22.0
#          image-name: zowe-docker-snapshot.jfrog.io/ompzowe/app-server:${{ github.event.inputs.image_tag }}
#          node-version:
          registry-user: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - uses: zowe-actions/shared-actions/docker-build-local@main
        with:
          dockerfile: ${{ github.workspace }}/docker-build-local/Dockerfile.sources
          build-arg-list: IMAGE_NAME=${{ github.event.inputs.image-name }} NODE_VERSION=${{ github.event.inputs.node-version }}
